version: '3.9'
services:
  mysql-customer-service:
    image:  mysql:latest
    container_name: mysql-customer-service
    networks:
      - my-network
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  user-authentication-service:
    image: user-auth
    container_name: user-authentication-service
    build:  ./
    networks:
      - my-network
    ports:
      - 8085:8085
    depends_on:
      - mysql-customer-service

networks:
  my-network:
    driver: bridge